### ISSUE TITLE
Wont resolve dependencies

### ISSUE THREAD

**Issue by julhad** [amelkor/Microsoft.Extensions.Hosting.Unity#1]
Hello @amelkor,

thanks for providing this. Can you please share a simple demo unity project? Somehow I can't get it to work, there is no game object created at runtime and no dependencies are resolved. 

Nevertheless the logging seems to work fine
 ```
<color=green>INFO [Microsoft.Hosting.Lifetime] - Application started. Press Ctrl+C to shut down.</color>
<color=green>INFO [Microsoft.Hosting.Lifetime] - Hosting environment: Production</color>
<color=green>INFO [Microsoft.Hosting.Lifetime] - Content root path: /Users/xyz/project</color>

<color=green>INFO [Microsoft.Hosting.Lifetime] - Application is shutting down...</color>
```

Im using Unity 2020.3.9f1 on macOS 11.3.1, maybe that's a problem?

Have a nice day!

**Comment by amelkor** [comment]
Sure, I'll push the demo I had for testing a bit later today

**Comment by amelkor** [comment]
Just discovered that I didn't push the latest fixes into the repo, so here they are now - please delete and install the package in your project again, that should resolve the issues.
Also check out the [demo project](https://github.com/amelkor/Microsoft.Extensions.Hosting.Unity-Demo) for examples.
Let me know if this works for you

**Comment by julhad** [comment]
Thanks for the demo, helped a lot :) 

Got it "working" now but sadly there seems to be an issue with unity and macOS or maybe something related with this. Starting the demo spawns the 15 cubes and then crashes unity instantly with 

> Failed to get ipc connection from UnityShaderCompiler shader compiler! /Applications/Unity/Hub/Editor/2020.3.9f1/Unity.app/Contents/Tools/UnityShaderCompiler
Launching external process: /Applications/Unity/Hub/Editor/2020.3.9f1/Unity.app/Contents/Tools/UnityShaderCompiler
No explicit failure code handling for error of type 22

If you deactivate the GameHost Script on the GameHost GameObject and reactive it once it is running it spawns the 15 cubes and does not crash and the "print message" button works too, but doing anything with the shader of the cubes instantly crashes unity with the same error 

> Shader compiler initialization error: Failed to get ipc connection from UnityShaderCompiler shader compiler! /Applications/Unity/Hub/Editor/2020.3.9f1/Unity.app/Contents/Tools/UnityShaderCompiler

**Comment by amelkor** [comment]
I got no mac to check unfortunately,you can try to change the DefaultExecutionOrder attribute value from -65500 to smth like -500 or whatever. Maybe on mac Unity needs to execute some internal scripts and that collides with the GameHost when it instantiates cubes. You can remove cubes instantiation from the demo, it's just an example.
Also, I usually create IHost and initialize all the services in a separate "Init" scene, just to be sure that all the stuff is prepared before the main/menu scene
